apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "receipt-scanner.name" . }}-redis
  labels:
    {{- include "receipt-scanner.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "receipt-scanner.name" . }}-redis
  labels:
    {{- include "receipt-scanner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
  selector:
    app: redis