apiVersion: v1
kind: Secret
metadata:
  name: {{ include "receipt-scanner.name" . }}-secrets
  labels:
    {{- include "receipt-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.secrets.botToken | quote }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.secrets.azureStorageConnectionString | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  REDIS_URL: "redis://{{ include "receipt-scanner.name" . }}-redis:{{ .Values.redis.port }}/0"

  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}

  DATABASE_URL: "postgresql+asyncpg://{{ .Values.secrets.postgresUser }}:{{ .Values.secrets.postgresPassword }}@{{ include "receipt-scanner.name" . }}-postgres:5432/{{ .Values.secrets.postgresDb }}"