apiVersion: v1
kind: Secret
metadata:
  name: {{ include "receipt-scanner.name" . }}-secrets
  labels:
    {{- include "receipt-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.secrets.botToken | quote }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.secrets.azureStorageConnectionString | quote }}
  REDIS_URL: "redis://{{ include "receipt-scanner.name" . }}-redis:{{ .Values.redis.port }}/0"