version: '3.8'

services:
  bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: receipt_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: receipt_celery_worker
    command: celery -A tasks.celery_app worker --loglevel=info
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: receipt_redis
    ports:
      - "6379:6379"
    restart: always